### ISSUE TITLE
table，有选择框时，当前只有一条记录时，剩下的空白列表，都有check选择框

### ISSUE THREAD

**Issue by Leadrive** [cairuoyu/flutter_admin#10]
这个如何去掉？

**Comment by cairuoyu** [comment]
看了PaginatedDataTable的源码，PaginatedDataTable是对DataTable的封装，当没数据时，还是会生成空行（_getBlankRowFor），但是会保存checkbok，所以如果使用PaginatedDataTable的话暂时无法去掉checkbox，期待flutter以后版本会处理这个问题

**Comment by cairuoyu** [comment]
考虑使用其它第三方组件
