### ISSUE TITLE
Run web 報錯

### ISSUE THREAD

**Issue by kuochaoyi** [cairuoyu/flutter_admin#15]
如下訊息, 再麻煩您了. 謝謝

很棒的後台展示. 

ENV: MacOS 11.4, M1

`
$ flutter run -d chrome --web-renderer html

Launching lib/main.dart on Chrome in debug mode...
lib/common/routes.dart:83:19: Error: The argument type 'List<GetPage<dynamic>>?' can't be assigned to the parameter type
'List<GetPage<dynamic>>' because 'List<GetPage<dynamic>>?' is nullable and 'List<GetPage<dynamic>>' isn't.
 - 'List' is from 'dart:core'.
 - 'GetPage' is from 'package:get/get_navigation/src/routes/get_route.dart'
 ('../../Downloads/flutter/.pub-cache/hosted/pub.dartlang.org/get-4.2.4/lib/get_navigation/src/routes/get_route.dart').
        children: layoutPages,
                  ^
Waiting for connection from debug service on Chrome...             19.8s
Failed to compile application.
`

**Comment by cairuoyu** [comment]
确定你获取的是最新的版本：https://github.com/cairuoyu/flutter_admin.git 或 git@github.com:cairuoyu/flutter_admin.git
因为5月20日之后的版本已处理null safety，而且报错的这段代码已作废了

**Comment by cairuoyu** [comment]
@kuochaoyi 已处理了，是我这边的文件pubspec.lock引用旧版本导致此问题没发现
