### ISSUE TITLE
UI 建议: 配色和字体调整一下

### ISSUE THREAD

**Issue by hhstore** [cairuoyu/flutter_admin#17]
- 项目整体完成度很高哇, 赞👍🏻 
- 使用了 GetX, 好评. 
    - 不过搜索了一下代码, 好像只有 `layout`, 用了一下 GetX, 还没用起来哇. 
    - 建议多用 GetX 写View, 以及路由接管, 数据状态管理. 
    - 早点用 GetX, 早点解脱. 😄 
- 几个小建议: 
    - UI 的配色, 不够好看.
    - 字体这个实在太丑了. 还是建议使用标准字体, 极度不适哇.  

## 几个 flutter 的 Admin UI: 

- http://phoenix2.yizimg.com/abuanwar072/Flutter-Responsive-Admin-Panel-or-Dashboard
    - https://abuanwar072.github.io/Flutter-Responsive-Admin-Panel-or-Dashboard/#/
    - 可以参考借鉴这个项目的`配色/字体`. 😄
- https://github.com/kalismeras61/flutter_web_dashboard
    - https://flutter-admin-panel-build.vercel.app/#/

## GetX 全家桶: 

- https://github.com/jonataslaw/getx
    - 框架本体 
    - 文档: https://github.com/jonataslaw/getx/blob/master/README.zh-cn.md
- https://github.com/jonataslaw/get_cli
    - 官方脚手架, 有时间, 可以用这个脚手架, 重写整个项目, 哈哈.  
- https://github.com/jonataslaw/get_storage
    - 非常好用的存储 
- https://github.com/jonataslaw/get_server
    - 后端 api server, 可以用它重新后端. 😄
- 我写过的一些关于 GetX 的文档: https://github.com/hhstore/blog/labels/GetX

**Comment by cairuoyu** [comment]
谢谢建议
- 路由管理已改为 Flutter Navigator 2
- 界面将会持续优化
- 默认的中文字体已去掉，但是可配置，界面也可下拉选择字体

**Comment by hhstore** [comment]
> 谢谢建议
> 
> * 路由管理已改为 Flutter Navigator 2
> * 界面将会持续优化
> * 默认的中文字体已去掉，但是可配置，界面也可下拉选择字体

赞.

- 字体可以配置化, 挺好的. 这样更灵活. 
- 持续关注. 😄
