### ISSUE TITLE
cry 和 flutter_quill 冲突，怎么解决？

### ISSUE THREAD

**Issue by fireFly201611** [cairuoyu/flutter_admin#19]
Because cry >=1.0.0 depends on image_picker ^0.7.3 and flutter_quill >=5.0.2 depends on image_picker ^0.8.5+3, cry >=1.0.0 is incompatible with flutter_quill >=5.0.2.
![image](https://user-images.githubusercontent.com/23520102/175487806-62057465-1a03-4b72-bdf2-d1cac3010c00.png)

**Comment by cairuoyu** [comment]
你可以在你的项目的pubspec.yaml里指定image_picker的版本，比如
dependency_overrides:
    image_picker ^0.8.5+3

**Comment by fireFly201611** [comment]
很高兴收到你的邮件，我会尽快查收回复的！
