### ISSUE TITLE
startup errors

### ISSUE THREAD

**Issue by hansbak** [cairuoyu/flutter_admin#2]
After starting the app, I get the following errors, do i miss something?

i entered: 
flutter create .
flutter run -d chrome

lib/pages/layout/layoutNoRoutes.dart:11:8: Error: Error when reading 'lib/utils/LocalStorageUtil.dart': No such file or directory
import 'package:flutter_admin/utils/LocalStorageUtil.dart';                                                        
       ^                                                                                                           
lib/pages/menu/menuMenu.dart:5:8: Error: Error when reading 'lib/components/CryTreeTable.dart': No such file or directory
import 'package:flutter_admin/components/CryTreeTable.dart';                                                       
       ^                                                                                                           
lib/pages/layout/layoutNoRoutes.dart:173:5: Error: The getter 'LocalStorageUtil' isn't defined for the class '_LayoutState'.
 - '_LayoutState' is from 'package:flutter_admin/pages/layout/layoutNoRoutes.dart' ('lib/pages/layout/layoutNoRoutes.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'LocalStorageUtil'. 
    LocalStorageUtil.set(Constant.KEY_TOKEN, null);                                                                
    ^^^^^^^^^^^^^^^^                                                                                               
lib/pages/menu/menuMenu.dart:29:10: Error: 'CryTreeTableColumnData' isn't a type.                                  
    List<CryTreeTableColumnData> columnData = [                                                                    
         ^^^^^^^^^^^^^^^^^^^^^^                                                                                    
lib/pages/menu/menuMenu.dart:30:7: Error: The method 'CryTreeTableColumnData' isn't defined for the class '_MenuMenuState'.
 - '_MenuMenuState' is from 'package:flutter_admin/pages/menu/menuMenu.dart' ('lib/pages/menu/menuMenu.dart').     
Try correcting the name to the name of an existing method, or defining a method named 'CryTreeTableColumnData'.    
      CryTreeTableColumnData('名称', (Menu v) => v.name),                                                          
      ^^^^^^^^^^^^^^^^^^^^^^                                                                                       
lib/pages/menu/menuMenu.dart:31:7: Error: The method 'CryTreeTableColumnData' isn't defined for the class '_MenuMenuState'.
 - '_MenuMenuState' is from 'package:flutter_admin/pages/menu/menuMenu.dart' ('lib/pages/menu/menuMenu.dart').     
Try correcting the name to the name of an existing method, or defining a method named 'CryTreeTableColumnData'.    
      CryTreeTableColumnData('英文名', (Menu v) => v.nameEn),                                                      
      ^^^^^^^^^^^^^^^^^^^^^^                                                                                       
lib/pages/menu/menuMenu.dart:32:7: Error: The method 'CryTreeTableColumnData' isn't defined for the class '_MenuMenuState'.
 - '_MenuMenuState' is from 'package:flutter_admin/pages/menu/menuMenu.dart' ('lib/pages/menu/menuMenu.dart').     
Try correcting the name to the name of an existing method, or defining a method named 'CryTreeTableColumnData'.    
      CryTreeTableColumnData('URL', (Menu v) => v.url),                                                            
      ^^^^^^^^^^^^^^^^^^^^^^                                                                                       
lib/pages/menu/menuMenu.dart:33:7: Error: The method 'CryTreeTableColumnData' isn't defined for the class '_MenuMenuState'.
 - '_MenuMenuState' is from 'package:flutter_admin/pages/menu/menuMenu.dart' ('lib/pages/menu/menuMenu.dart').     
Try correcting the name to the name of an existing method, or defining a method named 'CryTreeTableColumnData'.    
      CryTreeTableColumnData('顺序号', (Menu v) => v.orderBy?.toString(), width: 80),                              
      ^^^^^^^^^^^^^^^^^^^^^^                                                                                       
lib/pages/menu/menuMenu.dart:34:7: Error: The method 'CryTreeTableColumnData' isn't defined for the class '_MenuMenuState'.
 - '_MenuMenuState' is from 'package:flutter_admin/pages/menu/menuMenu.dart' ('lib/pages/menu/menuMenu.dart').     
Try correcting the name to the name of an existing method, or defining a method named 'CryTreeTableColumnData'.    
      CryTreeTableColumnData('备注', (Menu v) => v.remark, width: 300),                                            
      ^^^^^^^^^^^^^^^^^^^^^^                                                                                       
lib/pages/menu/menuMenu.dart:36:18: Error: The method 'CryTreeTable' isn't defined for the class '_MenuMenuState'. 
 - '_MenuMenuState' is from 'package:flutter_admin/pages/menu/menuMenu.dart' ('lib/pages/menu/menuMenu.dart').     
Try correcting the name to the name of an existing method, or defining a method named 'CryTreeTable'.              
    var result = CryTreeTable(                                                                                     
                 ^^^^^^^^^^^^

**Comment by cairuoyu** [comment]
谢谢，已处理了
这是大小写敏感问题 [https://github.com/flutter/flutter/issues/9539](https://github.com/flutter/flutter/issues/9539)
