### ISSUE TITLE
Error while trying to load an asset: Failed to load asset at "assets/config/application.yaml" (404)

### ISSUE THREAD

**Issue by LufeeWuKong** [cairuoyu/flutter_admin#23]
💪 Running with sound null safety 💪
Debug service listening on ws://127.0.0.1:49194/5o_az14jCtU=/ws
Error while trying to load an asset: Failed to load asset at "assets/config/application.yaml" (404)
Error: Unable to load asset: "config/application.yaml".
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 266:49  throw_
packages/flutter/src/services/asset_bundle.dart 254:9                         <fn>
dart-sdk/lib/async/zone.dart 1660:54                                          runUnary
dart-sdk/lib/async/future_impl.dart 147:18                                    handleValue
dart-sdk/lib/async/future_impl.dart 767:44                                    handleValueCallback
dart-sdk/lib/async/future_impl.dart 796:13                                    _propagateToListeners
dart-sdk/lib/async/future_impl.dart 567:5                                     [_completeWithValue]
dart-sdk/lib/async/future_impl.dart 640:7                                     callback
dart-sdk/lib/async/schedule_microtask.dart 40:11                              _microtaskLoop
dart-sdk/lib/async/schedule_microtask.dart 49:5                               _startMicrotaskLoop
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 166:15           <fn>

**Comment by cairuoyu** [comment]
这个是找不到路径的问题，请检查pubspec.yaml的assets是否有配置对应的路径
