### ISSUE TITLE
flutter pub get cry failed

### ISSUE THREAD

**Issue by trumpliu2018** [cairuoyu/flutter_admin#25]
[flutter_admin] flutter pub get
Resolving dependencies...
Because cry >=1.0.0 depends on intl ^0.17.0 and every version of flutter_localizations from sdk depends on intl 0.18.0, cry >=1.0.0 is incompatible with flutter_localizations from sdk.
So, because flutter_admin depends on both flutter_localizations from sdk and cry 1.2.0, version solving failed.
exit code 1

**Comment by cairuoyu** [comment]
已修复：[745a36e](https://github.com/cairuoyu/flutter_admin/commit/745a36ea3d5f82709c4d52b5d8c7ddc2a39f0a07)
