### ISSUE TITLE
编译成windows后，页面切换有跳动

### ISSUE THREAD

**Issue by Leadrive** [cairuoyu/flutter_admin#5]
比如现在打开角色管理和子系统管理两个页面。
点击顶部的tab栏，页面切换，跳动厉害。在切换过程中，还看到了登录的页面。
刚看了下，web也是有类似体验。这个建议改改。

另外，就是table/grid，建议满宽，按钮高度适当放大点。
可以参考下 https://github.com/syncfusion/flutter-widgets

做得不错，加油！

**Comment by cairuoyu** [comment]
谢谢
点击顶部的tab栏，页面切换，跳动厉害。在切换过程中，还看到了登录的页面。
--路由模式确实有这个问题，你可在右上角切换为无路由模式，我在考虑以后改为默认为无路由模式
另外，就是table/grid，建议满宽，按钮高度适当放大点。
--谢谢建议，以后会不断完善的
