### ISSUE TITLE
系统顶部按钮栏，按钮的tips，最后一个字母没显示出来。

### ISSUE THREAD

**Issue by Leadrive** [cairuoyu/flutter_admin#6]
如Setting，只显示了Settin

**Comment by Leadrive** [comment]
web没显示全，windows是全的

**Comment by cairuoyu** [comment]
谢谢
debug模式确实有这个问题，这可能是跟flutter版本有关，我记得以前版本是没这个问题的，升级到某个版本后才会出现
release模式就没这个问题了：http://www.cairuoyu.com/flutter_admin/
